server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql:///studb1?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/tencent/dao/mapper/*.xml